const itemList = [
	{
		name: "SIM Max Driver",
		category: "Driver",
		image:
			"https://www.taylormadegolf.com/on/demandware.static/-/Sites-tmag-master-catalog/en_US/v1605949646327/zoom/JJI27_zoom_D.jpg",
		price: 500,
		quantity: 0,
	},
	{
		name: "SIM Gloire Driver",
		category: "Driver",
		image: "https",
		price: 500,
		quantity: 0,
	},
	{
		name: "M6 Driver",
		category: "Driver",
		image: "https",
		price: 500,
		quantity: 0,
	},
	{
		name: "M5 Driver",
		category: "Driver",
		image: "https",
		price: 500,
		quantity: 0,
	},
	{
		name: "P790 Irons",
		category: "Iron",
		image: "https",
		price: 1400,
		quantity: 0,
	},
	{
		name: "P770 Irons",
		category: "Iron",
		image: "https",
		price: 1400,
		quantity: 0,
	},
	{
		name: "M2 Irons",
		category: "Iron",
		image: "https",
		price: 500,
		quantity: 0,
	},
	{
		name: "SIM DHY",
		category: "Iron",
		image: "https",
		price: 250,
		quantity: 0,
	},
	{
		name: "MG2 Tiger Woods Grind Wedge",
		category: "Wedge",
		image: "https",
		price: 200,
		quantity: 0,
	},
	{
		name: "Milled Grind 2 Wedge",
		category: "Wedge",
		image: "https",
		price: 170,
		quantity: 0,
	},
	{
		name: "MyHi-Toe Wedge",
		category: "Wedge",
		image: "https",
		price: 225,
		quantity: 0,
	},
	{
		name: "SIM Max OS Wedge",
		category: "Wedge",
		image: "https",
		price: 113,
		quantity: 0,
	},
	{
		name: "MySpider X",
		category: "Putter",
		image: "https",
		price: 420,
		quantity: 0,
	},
	{
		name: "Spider X Chalk",
		category: "Putter",
		image: "https",
		price: 350,
		quantity: 0,
	},
	{
		name: "Spider FCG",
		category: "Putter",
		image: "https",
		price: 350,
		quantity: 0,
	},
	{
		name: "TRUSS TB1",
		category: "Putter",
		image: "https",
		price: 300,
		quantity: 0,
	},
];

export default itemList;
