const itemList = [
	{
		name: "SIM Max Driver",
		category: "Driver",
		image: "https",
		price: "$500",
		quantity: 1,
	},
	{
		name: "SIM Gloire Driver",
		category: "Driver",
		image: "https",
		price: "$500",
		quantity: 1,
	},
	{
		name: "M6 Driver",
		category: "Driver",
		image: "https",
		price: "$500",
		quantity: 1,
	},
	{
		name: "M5 Driver",
		category: "Driver",
		image: "https",
		price: "$500",
		quantity: 1,
	},
	{
		name: "P790 Irons",
		category: "Iron",
		image: "https",
		price: "$1,400",
		quantity: 1,
	},
	{
		name: "P770 Irons",
		category: "Iron",
		image: "https",
		price: "$1,400",
		quantity: 1,
	},
	{
		name: "M2 Irons",
		category: "Iron",
		image: "https",
		price: "$500",
		quantity: 1,
	},
	{
		name: "SIM DHY",
		category: "Iron",
		image: "https",
		price: "$250",
		quantity: 1,
	},
	{
		name: "MG2 Tiger Woods Grind Wedge",
		category: "Wedge",
		image: "https",
		price: "$200",
		quantity: 1,
	},
	{
		name: "Milled Grind 2 Wedge",
		category: "Wedge",
		image: "https",
		price: "$170",
		quantity: 1,
	},
	{
		name: "MyHi-Toe Wedge",
		category: "Wedge",
		image: "https",
		price: "$225",
		quantity: 1,
	},
	{
		name: "SIM Max OS Wedge",
		category: "Wedge",
		image: "https",
		price: "$113",
		quantity: 1,
	},
	{
		name: "MySpider X",
		category: "Putter",
		image: "https",
		price: "$420",
		quantity: 1,
	},
	{
		name: "Spider X Chalk",
		category: "Putter",
		image: "https",
		price: "$350",
		quantity: 1,
	},
	{
		name: "Spider FCG",
		category: "Putter",
		image: "https",
		price: "$350",
		quantity: 1,
	},
	{
		name: "TRUSS TB1",
		category: "Putter",
		image: "https",
		price: "$300",
		quantity: 1,
	},
];

export default itemList;
